name: Deploy

on:
  push:

jobs:
  DocSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'adopt'
        uses: actions/setup-java@v2
      - name: Make site and scala doc
        run: sbt makeSite
      - name: Publish site
        run: |
          git config --global user.name "andrea-acampora"
          git config --global user.email "andrea.acampora@studio.unibo.it"
          sbt ghpagesPushSite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
