name: Deploy

on:
  push:

jobs:
  DocSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'adopt'
        uses: actions/setup-java@v3
      - name: Make site and scala doc
        run: sbt makeSite
      - name: Publish site
        run: sbt publishToGitHubPages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
